CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a web app', 1, 'Usando javascript', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make an app', 1, 'Usando dart', '2019-07-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a Desktop app', 2, 'Usando C++', '2015-05-12');

INSERT INTO tasks(name, done, projectId)
    VALUES('download vue.js', false, 1);
